---
title: "Introducción al lenguaje R con un enfoque espacial"
author: "Luis Balcázar"
date: "10/30/2020"
# widgets : [mathjax, quiz, bootstrap, interactive] # {mathjax, quiz, bootstrap}
# ext_widgets : {rCharts: [libraries/nvd3, libraries/leaflet, libraries/dygraphs]}
# mode : selfcontained # {standalone, draft}
output: ioslides_presentation
biglogo: uaemex.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

<!-- This is an R Markdown presentation. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>. -->

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document.

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

